### ISSUE TITLE
"cannot import name 'Jawbone'" error

### ISSUE THREAD

**Issue by Chattonne** [karthikbgl/python-jawbone-up#3]
I'm relatively new to Python, so apologies if I'm doing something wrong.

After installing this, when I do: from jawbone import Jawbone
I get the following

Traceback (most recent call last):
  File "jb.py", line 1, in <module>
    from jawbone import Jawbone
  File "C:\Python34\lib\site-packages\jawbone_up-0.1-py3.4.egg\jawbone__init__.py", line 1, in <module>
    from jawbone import Jawbone
ImportError: cannot import name 'Jawbone'

**Comment by karthikbgl** [comment]
yes, I am aware of that issue. Will work on a fix soon. In the meantime, you can just unzip the zip version provided at github (https://github.com/karthikbgl/python-jawbone-up/archive/master.zip) 
Sorry about that.

**Comment by Chattonne** [comment]
Ok thanks.

On Mon, Jun 30, 2014 at 3:52 PM, karthikbgl notifications@github.com
wrote:

> yes, I am aware of that issue. Will work on a fix soon. In the meantime,
> you can just unzip the zip version provided at github (
> https://github.com/karthikbgl/python-jawbone-up/archive/master.zip)
> Sorry about that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/karthikbgl/python-jawbone-up/issues/3#issuecomment-47578216
> .

## 

“When we remember that we are all mad, the mysteries disappear and life
stands explained.” - Mark Twain
